### ISSUE TITLE
CPU feature error

### ISSUE THREAD

**Issue by LyndonPrado** [saki4510t/UVCCamera#125]
when i try to run the program or export the program to an APK i always get the following errors:
[UVCErrorMessage.txt](https://github.com/saki4510t/UVCCamera/files/820365/UVCErrorMessage.txt)
 also the ndkBuildingDir in libuvccamera build.gradle cannot find the directory due to sdkHandler missing
![image](https://cloud.githubusercontent.com/assets/13879472/23601020/7b8ef860-029d-11e7-8e73-59a950519130.png)

**Comment by tairtec** [comment]
Saki has answered this question. in issue #130

**Comment by saki4510t** [comment]
@LyndonPrado 
Regarding issue of mips architecture, it was solved on latest master branch, #140 .
Regarding issue of sdkhandler, it was also already solved, #130  .
