### ISSUE TITLE
Camera with Y16 frame format is not previewing using libuvc for Android application

### ISSUE THREAD

**Issue by MSharief** [saki4510t/UVCCamera#135]
Hi,

I have a UVCcamera which supports the Y16 frame format with VGA Resolution and frame rate is 30 fps. am using libuvc to get the camera preview. But while calling this api "uvc_get_stream_ctrl_format_size" with "UVC_FRAME_FORMAT_YUYV" format,  return UVC_ERROR_INVALID_MODE.

could you please help me out how to negotiate(with which format) to get the camera preview successfully.

**Comment by MSharief** [comment]
I have implemented the required logic to Preview Y16 preview.

**Comment by Changseob** [comment]
@MSharief Could you share me Y16 supported code?

**Comment by namsangil** [comment]
@MSharief Can I get your code? Please.... help me. I need your code......
