### ISSUE TITLE
Wake lock not enabled  

### ISSUE THREAD

**Issue by freebumba27** [saki4510t/UVCCamera#142]
When camera is on screen light goes off. I am using usbCameraTest0. How can we keep it enable when camera is on?

**Comment by HalliGalliCestLaVie** [comment]
Did you try this?

http://stackoverflow.com/a/7596067

**Comment by freebumba27** [comment]
FULL_WAKE_LOCK is deprecated

**Comment by freebumba27** [comment]
resolved with this 

getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);
