### ISSUE TITLE
can not get correct descriptor

### ISSUE THREAD

**Issue by baopatrick** [saki4510t/UVCCamera#145]
I connect my camera to pixel xl by uvccameratest.it can find the camera and attaced. but can not open it.
the log as follow. can not find endpointaddress. can you give me some advice
04-07 16:43:14.129 6865-6943/com.serenegiant.usbcameratest D/UsbDeviceConnectionJNI: close
04-07 16:43:14.129 6865-6943/com.serenegiant.usbcameratest I/libUVCCamera: [6943*serenegiant_usb_UVCCamera.cpp:154:nativeConnect]:nativeConnect vid = 0x40e pid=0xf408
04-07 16:43:14.129 6865-6943/com.serenegiant.usbcameratest I/libusb/core: [6943*core.c:2085:libusb_init2]:libusb v1.0.19.10903
04-07 16:43:14.130 6865-6943/com.serenegiant.usbcameratest I/libusb/usbfs: [6943*android_usbfs.c:504:op_init2]:start up hotplug event handler
04-07 16:43:14.130 6865-6943/com.serenegiant.usbcameratest I/libusb/usbfs: [6943*android_usbfs.c:512:op_init2]:call android_scan_devices
04-07 16:43:14.130 6865-6943/com.serenegiant.usbcameratest I/libusb/usbfs: [6943*android_usbfs.c:514:op_init2]:call android_scan_devices return 0 
04-07 16:43:14.130 6865-6943/com.serenegiant.usbcameratest I/libuvc/device: [6943*device.c:279:uvc_open]:libusb_open() = 0
04-07 16:43:14.130 6865-6943/com.serenegiant.usbcameratest E/libuvc/device: [6943*device.c:382:uvc_get_device_info]:uvc_get_device_info
04-07 16:43:14.130 6865-6943/com.serenegiant.usbcameratest E/libuvc/device: [6943*device.c:331:uvc_open]:internal_devh->info->ctrl_if.bEndpointAddress is null

**Comment by DeboZhao** [comment]
How did you solve this problem?
