### ISSUE TITLE
error when build on windows

### ISSUE THREAD

**Issue by bitdust** [saki4510t/UVCCamera#16]
the [build.gradle](https://github.com/saki4510t/UVCCamera/blob/master/libuvccamera/build.gradle) can't work well on windows.

task ndkBuild in your [build.gradle](https://github.com/saki4510t/UVCCamera/blob/master/libuvccamera/build.gradle) could be better:

    import org.apache.tools.ant.taskdefs.condition.Os
    task ndkBuild(type: Exec, description: 'Compile JNI source via NDK') {
        def ndkDir = project.plugins.findPlugin('com.android.library').sdkHandler.getNdkFolder()
        println(ndkDir)
        if (Os.isFamily(Os.FAMILY_WINDOWS)) {
            commandLine "$ndkDir/ndk-build.cmd",
                    'NDK_PROJECT_PATH=build',
                    'APP_BUILD_SCRIPT=src/main/jni/Android.mk',
                    'NDK_APPLICATION_MK=src/main/jni/Application.mk',
                    '-j8'
        }
        else {
            commandLine "$ndkDir/ndk-build",
                    'NDK_PROJECT_PATH=build',
                    'APP_BUILD_SCRIPT=src/main/jni/Android.mk',
                    'NDK_APPLICATION_MK=src/main/jni/Application.mk',
                    '-j8'
        }
    }

than:

    task ndkBuild(type: Exec, description: 'Compile JNI source via NDK') {
        def ndkDir = project.plugins.findPlugin('com.android.library').sdkHandler.getNdkFolder()
        println(ndkDir)
        commandLine "$ndkDir/ndk-build",
                'NDK_PROJECT_PATH=build',
                'APP_BUILD_SCRIPT=src/main/jni/Android.mk',
                'NDK_APPLICATION_MK=src/main/jni/Application.mk',
                '-j8'
    }

Refer to:https://stackoverflow.com/questions/27477158/android-studio-ndk-build-trouble-errorexecution-failed-for-task-appbuildnati

**Comment by Darksideneo** [comment]
It works fine on Windows if you will correct paths in the right way. I can
show how tomorrow.

**Comment by saki4510t** [comment]
Hi, thank you for providing feedback.  
I updated build.grade in libuvccamera.  
saki
