### ISSUE TITLE
usbCameratest7 cleanup

### ISSUE THREAD

**Issue by btut** [saki4510t/UVCCamera#18]
Hi saki,
I have noticed that there is some inconsistency in your project structure. usbCameratest7 is the only sample project where the first 't' is in lower case, all other projects have a uppercase 'T'. Nevertheless, the file usbCameraTest7.iml has a uppercase 'T' just as the others. This messes up the AndroidStudio setup. Everytime I include this project, AndroidStudio creates a usbCameraTest7 Folder (note the upper case 'T') and searches for all files in that folder, of course without success.
Could you please clean this up in your master branch? Renaming the folder 'usbCameratest7' to 'usbCameraTest7' resolves all issues.
Thanks!

**Comment by saki4510t** [comment]
Hi,
Thank you for providing notification. I renamed.  
I usually use OSX and it just ignores case of file name and directory name...
saki

**Comment by btut** [comment]
Thanks!
I am using OS X as well but it was causing problems.
On Oct 11, 2015 6:43 PM, saki <notifications@github.com> wrote:Closed #18.
