### ISSUE TITLE
Blank? Glitch images occur sometimes

### ISSUE THREAD

**Issue by sappho192** [saki4510t/UVCCamera#192]
Sometimes blank(or glitch) images with partial grey coloured area and partial images through camera occur. Is this out of performance issue? Does anyone experienced this?
My phone is Samsung Galaxy S7 and the camera is dual-lens camera from here: https://www.aliexpress.com/item/Synchronization-USB-3-0-MJPEG-30fps-2560-720-OV9714-CMOS-mini-webcam-Dual-lens-usb-camera/32642278164.html?spm=2114.13010608.0.0.z4YcXw
Thanks.

**Comment by RogerHardiman** [comment]
I get the same problem too with a single camera uvc camera and have seen it on several different handselts. I think it must be down to the volume of data on the USB bus.
I did try switching from YUYV format (raw data) to the MJPEG modes (which than incurs CPU time to decompress the JPEGs) but from memory both had occasional glitches.

**Comment by obg2sens** [comment]
Maybe it is same issue as this https://github.com/saki4510t/UVCCamera/issues/127

**Comment by sappho192** [comment]
@RogerHardiman @obg2sens What's the resolution of your camera video settings?

**Comment by RogerHardiman** [comment]
640x400  (this is why I modified one of the example programs to select a valid resolution instead of being hard coded to 640x480)
