### ISSUE TITLE
Read the contrast while previewing causing the preview looks strange

### ISSUE THREAD

**Issue by andymatos** [saki4510t/UVCCamera#206]
I am doing some tests based on usbCameraTest8. My purpose is to get the brightness of each frame.So I add some codes to make it possible to set IFrameCallback through UVCCameraHandler and in the callback, I try to read the brightness when the frame is read like this
    private final IFrameCallback mIFrameCallback = new IFrameCallback() {
        @Override
        public void onFrame(final ByteBuffer frame) {
            int br = mCameraHandler.getValue(UVCCamera.PU_BRIGHTNESS);
            Log.v(TAG, "br: " + Integer.toString(br));
        }
    };

It reads brightness successfully, but also causes the preview not displayed correctly.The preview looks like a combination of two adjacent frame.
If I remove the getValue function in callback, all works fine. So I think, maybe it is because the read command takes too much time? Should I stop previewing before sending the read command and start previewing aging after the read command is finished?
Or may there is a way to block the read command while streaming?
I'd like to know the correct way to do this.Can anyone help on this?

**Comment by sappho192** [comment]
So many people(+me) asks about that and [https://github.com/saki4510t/UVCCamera/issues/165](https://github.com/saki4510t/UVCCamera/issues/165) someone told solution.
I'm trying to solve this but not easy.... Please let us know if you solve this problem.
