### ISSUE TITLE
Is there anyone who converted frame data(RGB565 or NV21) to ARGB8888 to manipulate them?

### ISSUE THREAD

**Issue by sappho192** [saki4510t/UVCCamera#208]
Hi,

I'm going to process each frame data in native C side, so it is necessary to convert the format of each data.
Currently I can achieve RGB565 or NV21 formatted frames so tried to convert them to ARGB8888 but it failed.
The reference of RGB565 -> ARGB8888 is nearly don't exist and NV21 -> ARGB8888 is [here](https://github.com/arrayfire/androidcl/blob/master/assets/kernels.cl) but it doesn't work on this project.
Am I missing something?

Any advice can help me a lot.

**Comment by sappho192** [comment]
Solved it.

Check this repository. https://github.com/arrayfire/androidcl/blob/master/assets/kernels.cl

**Comment by vongohren** [comment]
This is a while ago, but you did not find any other ways?
