### ISSUE TITLE
Camera Preview is not working with some webcam.

### ISSUE THREAD

**Issue by aviontechnology** [saki4510t/UVCCamera#214]
Hello,
I use UVCCamera to connect external webcam in my project.
But its not working with some webcam.
1.Logitech V-U0024 and 2.Microsoft Life Cam VX-700.

So How can i make it work with any webcam. 
Please give me some solution for this.

Thank You

**Comment by sappho192** [comment]
1. Be sure you are not using NDK 15, but NDK 14b
2. https://github.com/saki4510t/UVCCamera/pull/175 apply this code change to get rid of resolution issue.
3. Provide your log or clues

**Comment by aviontechnology** [comment]
Yes, i am using NDK 15
Pkg.Desc = Android NDK
Pkg.Revision = 15.1.4119039

Which NDK Version I need to use.

**Comment by sappho192** [comment]
Use NDK 14b. You can manually assign the location of NDK in "Project Structure" in Android Studio.

**Comment by aviontechnology** [comment]
Hello,

As you suggest i did changes with NDK and now i am using NDK 14b. 
I use usbCameraTest8's MainActivity.java in my project.
There is no 	**private UVCCamera mUVCCamera;** object.
In  usbCameraTest8not use UVCCamera
thats why i can not possible to use 2. [#175](https://github.com/saki4510t/UVCCamera/pull/175) apply.

So please give me one solution which work with **usbCameraTest8's MainActivity.java**

Thank You
Kiran Kirve

**Comment by sappho192** [comment]
#175 's patch is getting best resolution that your camera supports.
If you know supported resolution of your camera, then just overwrite it to width and height variables.

**Comment by aviontechnology** [comment]
I am looking solution which work for all web cams.

**Comment by sappho192** [comment]
Then make the code like #175 .
