### ISSUE TITLE
Can I keep the camera working without setting the Surface(hide UI)?

### ISSUE THREAD

**Issue by lb5160482** [saki4510t/UVCCamera#233]
If I want to hide the image view and do some image processing(I do not want the UI part), how can I make the camera working?
I tried removing the Surface, then the camera was not working.

**Comment by sikrinick** [comment]
Are you using based on UVCCamera or UVCCameraHandler class?

**Comment by lb5160482** [comment]
@sikrinick either is fine. I am now using UVCCameraHandler class.

**Comment by sappho192** [comment]
Early I faced this problem and solved it like setting preview UI size as 0px * 0px (width * height)? 1px * 1px?

**Comment by lb5160482** [comment]
@sappho192 Thanks! Yeah I tried this before and it worked. What  I am facing now is I am going to build a camera plugin for Unity. In that way, the UI is generated by Unity, where probably I have no access to the XML layout file. I can manually add the surface component on Java side and then set the size 1 pixel. But I am wondering if I can totally get rid of it?

**Comment by xiaochongdeweiba** [comment]
usbcameratest4 can do this

**Comment by lb5160482** [comment]
Solved by using [here](https://github.com/TimGroeneboom/libuvc_android_unity).

**Comment by MarcBS** [comment]
@lb5160482 it seems that the link you provided as a solution is no longer available. Could you please share an updated link or a snippet? 

That would be very helpful!
