### ISSUE TITLE
Getting black screen with Samsung Galaxy A and J series 

### ISSUE THREAD

**Issue by dioi2000** [saki4510t/UVCCamera#256]
Hi Saki,

thank you for your project

its really work well but I have a problem that getting black screen with some device
(Galaxy A and J series and some of LG phones such as Nexus5X)

camera connected well but It's getting only black screen
I'm not sure what is the problem but it can't initialize setPreviewSize and I don't know how to fix it

saki4510t I need your help
thanks.

**Comment by jp1017** [comment]
logs?

**Comment by dioi2000** [comment]
@jp1017 here is a log

10-31 15:54:09.408 2804-5642/? W/System.err: java.lang.IllegalArgumentException: Failed to set preview size
10-31 15:54:09.413 2804-5642/? W/System.err:     at com.serenegiant.usb.UVCCamera.setPreviewSize(UVCCamera.java:328)
10-31 15:54:09.413 2804-5642/? W/System.err:     at com.serenegiant.usb.UVCCamera.setPreviewSize(UVCCamera.java:299)
10-31 15:54:09.414 2804-5642/? W/System.err:     at com.unichal.bookcam.service.UVCManager$1.onConnect(UVCManager.java:197)
10-31 15:54:09.414 2804-5642/? W/System.err:     at com.serenegiant.usb.USBMonitor$3.run(USBMonitor.java:574)
10-31 15:54:09.414 2804-5642/? W/System.err:     at android.os.Handler.handleCallback(Handler.java:789)
10-31 15:54:09.414 2804-5642/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
10-31 15:54:09.414 2804-5642/? W/System.err:     at android.os.Looper.loop(Looper.java:164)
10-31 15:54:09.414 2804-5642/? W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:65)

++ sample 1,4 work well but others shutdown with error

**Comment by jp1017** [comment]
> Failed to set preview size

**Comment by dioi2000** [comment]
@jp1017 
I Know but I wanna know why failed and how to fix it

**Comment by jp1017** [comment]
You may get the supported size in logs. 

So, What's the preview size you set?

**Comment by dioi2000** [comment]
here is a supported size and preview size I set

supportedSize:{"formats":[{"index":1,"type":4,"default":1,"size":["640x480","352x288","320x240","176x144","160x120"]}]}

UVCCamera.DEFAULT_PREVIEW_WIDTH, UVCCamera.DEFAULT_PREVIEW_HEIGHT

**Comment by dioi2000** [comment]
our source used old version of library
