### ISSUE TITLE
Native Memory leak

### ISSUE THREAD

**Issue by xiaozhi003** [saki4510t/UVCCamera#259]
Repeat it again and again.Native memory keeps growing and cause #244 .Android Studio3.0 can detect that.
@saki4510t Please help me,ths.
![image](https://user-images.githubusercontent.com/4998101/32306064-43eef232-bfb4-11e7-883c-4a7b7af8840b.png)

**Comment by xiaozhi003** [comment]
OK，I found this bug
**UVCPreview.cpp**
```C
void UVCPreview::addCaptureFrame(uvc_frame_t *frame) {
	pthread_mutex_lock(&capture_mutex);
	if (LIKELY(isRunning())) {
		// keep only latest one
		if (captureQueu) {
			recycle_frame(captureQueu);
		}
		captureQueu = frame;
		pthread_cond_broadcast(&capture_sync);
	} else {
	    // Add this can sovle native leak 
	    recycle_frame(frame);
	}

	pthread_mutex_unlock(&capture_mutex);
}
```

**Comment by qiqisteve** [comment]
好像这个不起作用，还是有内存泄漏，及时不关闭都有

**Comment by BarryAlertPan** [comment]
I also encountered this problem, how do you solve it?

**Comment by xiaozhi003** [comment]
@BarryAlertPan According to the above modified source code **UVCPreview.cpp**

**Comment by xiaozhi003** [comment]
@qiqisteve  这里肯定是有问题的，我改了这里循环开关24小时没有出现问题过，内存涨不过1-2M。还有一个linux文件句柄不能打开太多次（具体多少忘了好像是900次）否则报too many open files，所以**UsbControlBlock**也是可以复用的，不用每次都生成一个新的对象

**Comment by myHelloer** [comment]
@xiaozhi003 你好，想问下关于UsbControlBlock的复用是怎么处理的啊

**Comment by alless1** [comment]
It really doesn't work. My native heap keeps rising and can't be released.
Please help me。

**Comment by YiZhou213** [comment]
After Modify 
---void UVCPreview::do_capture_callback(JNIEnv *env, uvc_frame_t *frame) {
ENTER();if (LIKELY(frame)) {
	uvc_frame_t *callback_frame = frame;
	if (mFrameCallbackObj) {
		if (mFrameCallbackFunc) {
			callback_frame = get_frame(callbackPixelBytes);
			if (LIKELY(callback_frame)) {
				int b = mFrameCallbackFunc(frame, callback_frame);
				recycle_frame(frame);
				if (UNLIKELY(b)) {
					LOGW("failed to convert for callback frame");
					goto SKIP;
				}
			} else {
				LOGW("failed to allocate for callback frame");
				callback_frame = frame;
				goto SKIP;
			}
		}
		jobject buf = env->NewDirectByteBuffer(callback_frame->data, callbackPixelBytes);
		pthread_mutex_lock(&capture_mutex);
		if(iframecallback_fields.onFrame != NULL){
			env->CallVoidMethod(mFrameCallbackObj, iframecallback_fields.onFrame, buf);
		}
		pthread_mutex_unlock(&capture_mutex);
		env->ExceptionClear();
		env->DeleteLocalRef(buf);
	}

And
void UVCPreview::addCaptureFrame(uvc_frame_t *frame) {
		}
		captureQueu = frame;
		pthread_cond_broadcast(&capture_sync);
	} else {
	    // Add this can sovle native leak
	    recycle_frame(frame);
	}

	pthread_mutex_unlock(&capture_mutex);
}
 
My native heap keeps rising too   and can't be released.

**Comment by hugoleong** [comment]
感谢，解决了我遇到的问题！！！
