### ISSUE TITLE
Take Snap While Video Rendering

### ISSUE THREAD

**Issue by dalwadi2** [saki4510t/UVCCamera#269]
Hello, 

I'm using **SurfaceView** for rendering video and while rendering the video I want to take a **snap** (what is there on Video) at some point. Can anyone suggest me how can I take a **snap** while I'm rendering the Video on **SurfaceView**

**Comment by MaximilianReason** [comment]
What you're trying to do can be achieved by using the IFrameCallback feature. Refer to this: https://github.com/saki4510t/UVCCamera/wiki/howto_create_bitmap_using_iframecallback for details.

**Comment by dalwadi2** [comment]
Yeh Sure @MaximilianReason 
thanks
