### ISSUE TITLE
Unable to build project

### ISSUE THREAD

**Issue by ravikumarg45** [saki4510t/UVCCamera#304]
Hi , I am trying to build the project. but i get the following error:

Error:Could not resolve all files for configuration ':libuvccamera:debugCompileClasspath'.
> Could not resolve com.serenegiant:common:1.5.20.
  Required by:
      project :libuvccamera
   > Could not resolve com.serenegiant:common:1.5.20.
      > Could not get resource 'http://raw.github.com/saki4510t/libcommon/master/repository/com/serenegiant/common/1.5.20/common-1.5.20.pom'.
         > Could not GET 'http://raw.github.com/saki4510t/libcommon/master/repository/com/serenegiant/common/1.5.20/common-1.5.20.pom'. Received status code 403 from server: Forbidden
   > Could not resolve com.serenegiant:common:1.5.20.
      > Could not get resource 'https://jcenter.bintray.com/com/serenegiant/common/1.5.20/common-1.5.20.pom'.
         > Could not GET 'https://jcenter.bintray.com/com/serenegiant/common/1.5.20/common-1.5.20.pom'.
            > Connection reset

**Comment by jp1017** [comment]
Try version 1.5.4

**Comment by ravikumarg45** [comment]
Firewall issue, works fine.
