### ISSUE TITLE
Camera Service does not run after refactoring the project usbCameraTest4

### ISSUE THREAD

**Issue by ritchie-w** [saki4510t/UVCCamera#339]
Hi,

I refactoring the testprogram "usbCameraTest4" to my own project name in the following way,
"Project"-Master

-"Project" 
-------../Java
-------------com
-----------------"Project"
-----------------serenegiant
--------------------service
--------------------serviceclient
-------../res
- libuvccamera
- usbCameraCommon

The building works fine, but the application does not start the "CameraServer", so 
no stream is shown.

When I install the original Example usbCameraTest4, my application is working as well.
Looks for my, this I do not install the service "serenegiant" not correct.

Edit:
I guess, that this lines are not working correctly:

	final Intent intent = new Intent(IUVCService.class.getName());
	intent.setPackage("com.serenegiant.usbcameratest4");
	context.bindService(intent,
	mServiceConnection, Context.BIND_AUTO_CREATE);

In Module: CameraClient
I have used my project name at the "intent.setPackage" line.

Where is my failure ?
Best regards
R.

**Comment by ritchie-w** [comment]
I found the reason in the AndroidManifest.xml.

                <action android:name="com.<Project>.service.IUVCService" />
                <action android:name="com.<Project>.service.IUVCSlaveService" />

Sorry. Is my first Android project.

**Comment by ADUOH2017** [comment]
Hi ritchie-w,

I am also a begginner in android deveelopper and I have a problem with usbCameraTest4.

First of all,  it compiled correctly and installed in my ohone but it is crashed and  I don't know what is the problem.

Can you help me please.
It is very urgent.
Thank you very much in advance
