### ISSUE TITLE
Can't Import the library in Android Studio

### ISSUE THREAD

**Issue by boredomdenied** [saki4510t/UVCCamera#361]
I've been at this for the last 24hrs now with no success. I've looked at issues here, at relevant resources online, at the README and WIKI, and nothing has ever worked. 

This should not be so difficult to use. I've tried creating/importing AARs, tried importing/creating new modules through at least a dozen variations.. yes I've modified the Applications.mk file to actually compile the project (why does it still contain obsolete flags?), and yes I can find success simply cloning the project and running it through the test projects. 

There does not appear to be a single sane method of importing these modules into your own project. If someone can please come up with a simple step by step process, let me know. 

https://github.com/saki4510t/UVCCamera/wiki/When-you-import-libuvccamera-module-in-your-project-instead-of-building-these-samples-from-this-repository

That is not a solution. It does not work. Period

```
Failed to resolve: com.serenegiant:common:1.4.3
```

**Comment by boredomdenied** [comment]
resolved. I'm too noob

**Comment by John-Pandian** [comment]
> resolved. I'm too noob

How did you resolve it??
