### ISSUE TITLE
 open failed:result=-1

### ISSUE THREAD

**Issue by fuliteng** [saki4510t/UVCCamera#380]
FATAL EXCEPTION: CameraThread
06-29 10:37:05.797  4359  4496 E AndroidRuntime: Process: com.serenegiant.usbcameratest4:uvcservice, PID: 4359
06-29 10:37:05.797  4359  4496 E AndroidRuntime: Theme: themes:{}
06-29 10:37:05.797  4359  4496 E AndroidRuntime: java.lang.UnsupportedOperationException: open failed:result=-1
06-29 10:37:05.797  4359  4496 E AndroidRuntime:        at com.serenegiant.usb.UVCCamera.open(UVCCamera.java:204)
06-29 10:37:05.797  4359  4496 E AndroidRuntime:        at com.serenegiant.service.CameraServer$CameraThread.handleOpen(CameraServer.java:379)
06-29 10:37:05.797  4359  4496 E AndroidRuntime:        at com.serenegiant.service.CameraServer.handleMessage(CameraServer.java:262)
06-29 10:37:05.797  4359  4496 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
06-29 10:37:05.797  4359  4496 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
06-29 10:37:05.797  4359  4496 E AndroidRuntime:        at com.serenegiant.service.CameraServer$CameraThread.run(CameraServer.java:632)

**Comment by WeileLiang** [comment]
@fuliteng Could you please how to fix this problem? THX!
