### ISSUE TITLE
How to start the preview instantly without clicking the camera button and showing select the web carera ?

### ISSUE THREAD

**Issue by FFYzz** [saki4510t/UVCCamera#420]
Just as described above, I want to get the video stream instantly without any extra operating. In other word, I just want to see the video stream when I open the APP. Also I want to get the frame data. What should I do with the project? Any help will be appreciated.

**Comment by rgm-22** [comment]
Hi FFYzz!
Did you obtain any progress with this? It's a good idea!

**Comment by Guizzz** [comment]
Hi, did you find a solution? I want to do the same thing but i don't know how.
