### ISSUE TITLE
UVCCamera7 not always works on my samsung s4.

### ISSUE THREAD

**Issue by sudharsan06** [saki4510t/UVCCamera#44]
UVCCamera7 works good on webcam C270 for first time. But After Some time UVCCamera7 dialogs "No USB Camera found" message. Some times it working , some time not , I don't know that what is the exact reason for this errror and i not able to find solution for that. 

I got the same problem when i tested using webcam pro 9000.
![screenshot_2016-03-03-12-55-08](https://cloud.githubusercontent.com/assets/17610495/13487727/2d315da2-e142-11e5-916c-666688ca165c.png)

**Comment by sudharsan06** [comment]
For connectivity i using USB 2 . There is no issues on connectivity!

**Comment by saki4510t** [comment]
Hi,
I update many things today, mainly to support Android 6 and Android7. This also my be fixed.
So I close this once. I you still have trouble, please re-open or make new issue.
saki
