### ISSUE TITLE
Jni does not call java callback in time

### ISSUE THREAD

**Issue by pdyw** [saki4510t/UVCCamera#447]
UVCPreview::do_capture_callback 不及时调用java onFrame 方法,我设置Min_Fps=10,Max_Fps=20,但是java回调1s中只有2-3次，但是在do_capture_callback加了一LOG日志，就正常了，为什么?

**Comment by pdyw** [comment]
android log bug 同一时间数据一样，或间断打印

**Comment by dongyi190120** [comment]
非常感谢。遇到同样问题。
