### ISSUE TITLE
How can I rename test4?

### ISSUE THREAD

**Issue by ghost** [saki4510t/UVCCamera#450]
Hi, I using test4 for my own project and want to rename about application's name.
I know I can change label at the strings.xml but I also want to change service permission how can I change it?
![Screenshot_20190312-155255_USBCameraTest4_test](https://user-images.githubusercontent.com/43158295/54180497-2a532a80-44df-11e9-8d7f-974acbccc200.jpg)

**Comment by lvi166** [comment]
The first you should rename package. if you dont know how to do it , please search in google .and do 
[clean project]  [rebuild project]
 in Android Studio。

**Comment by ghost** [comment]
@lvi166 I also already try that several times(with https://stackoverflow.com/questions/14610013/change-package-name-of-java-and-aidl-files and https://stackoverflow.com/questions/16804093/rename-package-in-android-studio) but when I did that, then I couldn't see permission dialog.
Logs are only show like below. I changed only package's name.
03-18 14:47:01.478 17077-17077/? E/Zygote: isWhitelistProcess - Process is Whitelisted
03-18 14:47:01.479 17077-17077/? E/libpersona: scanKnoxPersonas
    Couldn't open the File - /data/system/users/0/personalist.xml - No such file or directory
03-18 14:47:01.482 17077-17077/? W/SELinux: SELinux selinux_android_compute_policy_index : Policy Index[2],  Con:u:r:zygote:s0 RAM:SEPF_SM-G930K_8.0.0_0018, [-1 -1 -1 -1 0 1]
03-18 14:47:01.483 17077-17077/? I/SELinux: SELinux: seapp_context_lookup: seinfo=untrusted, level=s0:c512,c768, pkgname=com.testRn.servicetest 
03-18 14:47:01.486 17077-17077/? I/zygote: Late-enabling -Xcheck:jni
03-18 14:47:01.534 17077-17077/? D/TimaKeyStoreProvider: TimaKeyStore is not enabled: cannot add TimaSignature Service and generateKeyPair Service
03-18 14:47:01.535 17077-17077/? D/ActivityThread: Added TimaKeyStore provider
03-18 14:47:01.558 17077-17090/? E/zygote: Failed sending reply to debugger: Broken pipe
03-18 14:47:01.559 17077-17090/? I/zygote: Debugger is no longer active
03-18 14:47:01.591 17077-17077/? I/zygote: no shared libraies, dex_files: 1
03-18 14:47:01.738 17077-17077/? V/CameraFragment: Constructor:
03-18 14:47:01.739 17077-17077/? V/CameraFragment: onAttach:
    onCreate:
03-18 14:47:01.744 17077-17077/? V/CameraFragment: onCreateView:
03-18 14:47:01.802 17077-17077/? V/CameraFragment: onResume:
03-18 14:47:01.815 17077-17133/? D/OpenGLRenderer: HWUI GL Pipeline
03-18 14:47:01.832 17077-17077/? D/ViewRootImpl@c2e6e47[MainActivity]: setView = DecorView@748c674[MainActivity] TM=true MM=false
03-18 14:47:01.849 17077-17077/? D/ViewRootImpl@c2e6e47[MainActivity]: dispatchAttachedToWindow
03-18 14:47:01.867 17077-17077/? V/Surface: sf_framedrop debug : 0x4f4c, game : false, logging : 0
03-18 14:47:01.868 17077-17077/? D/ViewRootImpl@c2e6e47[MainActivity]: Relayout returned: old=[0,0][0,0] new=[0,0][1080,1920] result=0x7 surface={valid=true 3517509632} changed=true
03-18 14:47:01.872 17077-17133/? I/OpenGLRenderer: Initialized EGL, version 1.4
03-18 14:47:01.872 17077-17133/? D/OpenGLRenderer: Swap behavior 2
03-18 14:47:01.876 17077-17133/? D/libGLESv1: STS_GLApi : DTS, ODTC are not allowed for Package : com.testRn.servicetest
03-18 14:47:01.876 17077-17133/? D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [1080x1920]-format:1
03-18 14:47:01.876 17077-17133/? D/OpenGLRenderer: eglCreateWindowSurface = 0xd095e028
03-18 14:47:01.881 17077-17077/? D/SurfaceView: BG show() Surface(name=Background for - SurfaceView - com.testRn.servicetest/com.testRn.servicetest.MainActivity@5b436a@0) android.view.SurfaceView{5b436a VFE...C.. ......ID 753,459-1053,759 #7f08002b app:id/camera_view_sub}
03-18 14:47:01.897 17077-17077/? V/Surface: sf_framedrop debug : 0x4f4c, game : false, logging : 0
03-18 14:47:01.897 17077-17077/? D/SurfaceView: surfaceCreated 0 android.view.SurfaceView{5b436a VFE...C.. ......ID 753,459-1053,759 #7f08002b app:id/camera_view_sub}
03-18 14:47:01.898 17077-17077/? D/SurfaceView: surfaceChanged (300,300) 0 android.view.SurfaceView{5b436a VFE...C.. ......ID 753,459-1053,759 #7f08002b app:id/camera_view_sub}
03-18 14:47:01.916 17077-17077/? D/ViewRootImpl@c2e6e47[MainActivity]: Relayout returned: old=[0,0][1080,1920] new=[0,0][1080,1920] result=0x3 surface={valid=true 3517509632} changed=false
03-18 14:47:01.920 17077-17077/? V/Surface: sf_framedrop debug : 0x4f4c, game : false, logging : 0
03-18 14:47:01.920 17077-17077/? V/UVCCameraTextureView: onSurfaceTextureAvailable:android.graphics.SurfaceTexture@7cea9d1
03-18 14:47:01.921 17077-17077/? V/UVCCameraTextureView: RenderThread#getHandler:
03-18 14:47:01.921 17077-17161/? D/UVCCameraTextureView: RenderThread started
03-18 14:47:01.921 17077-17161/? V/UVCCameraTextureView: RenderThread#init:
03-18 14:47:01.921 17077-17161/? V/UVCCameraTextureView: RenderThread#init:
03-18 14:47:01.923 17077-17161/? D/EGLBase14: EGLContext created, client version 3
03-18 14:47:01.924 17077-17161/? V/Surface: sf_framedrop debug : 0x4f4c, game : false, logging : 0
03-18 14:47:01.924 17077-17161/? D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [1056x791]-format:1
03-18 14:47:01.998 17077-17077/? D/ViewRootImpl@c2e6e47[MainActivity]: MSG_RESIZED_REPORT: frame=Rect(0, 0 - 1080, 1920) ci=Rect(0, 72 - 0, 0) vi=Rect(0, 72 - 0, 0) or=1
    MSG_WINDOW_FOCUS_CHANGED 1
03-18 14:47:02.004 17077-17077/? V/InputMethodManager: Starting input: tba=android.view.inputmethod.EditorInfo@3622c36 nm : com.testRn.servicetest ic=null
03-18 14:47:02.004 17077-17077/? I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
03-18 14:47:02.020 17077-17077/? V/InputMethodManager: Starting input: tba=android.view.inputmethod.EditorInfo@2097737 nm : com.testRn.servicetest ic=null
03-18 14:47:11.530 17077-17077/com.testRn.servicetest V/CameraFragment: onPause:
03-18 14:47:11.549 17077-17077/com.testRn.servicetest D/SurfaceView: BG show() Surface(name=Background for - SurfaceView - com.testRn.servicetest/com.testRn.servicetest.MainActivity@5b436a@0) android.view.SurfaceView{5b436a VFE...C.. ........ 753,459-1053,759 #7f08002b app:id/camera_view_sub}
03-18 14:47:11.550 17077-17077/com.testRn.servicetest D/SurfaceView: surfaceDestroyed 0 android.view.SurfaceView{5b436a VFE...C.. ........ 753,459-1053,759 #7f08002b app:id/camera_view_sub}
03-18 14:47:11.550 17077-17077/com.testRn.servicetest V/CameraFragment: onDestroyView:
03-18 14:47:11.551 17077-17077/com.testRn.servicetest V/UVCCameraTextureView: onSurfaceTextureDestroyed:android.graphics.SurfaceTexture@7cea9d1
    release:
03-18 14:47:11.551 17077-17161/com.testRn.servicetest D/UVCCameraTextureView: RenderThread finishing
03-18 14:47:11.551 17077-17161/com.testRn.servicetest V/UVCCameraTextureView: RenderThread#release:
03-18 14:47:11.563 17077-17077/com.testRn.servicetest D/SurfaceView: BG show() Surface(name=Background for - SurfaceView - com.testRn.servicetest/com.testRn.servicetest.MainActivity@5b436a@0) android.view.SurfaceView{5b436a VFE...C.. ........ 753,459-1053,759 #7f08002b app:id/camera_view_sub}
03-18 14:47:11.565 17077-17077/com.testRn.servicetest D/SurfaceView: BG destroy() Surface(name=Background for - SurfaceView - com.testRn.servicetest/com.testRn.servicetest.MainActivity@5b436a@0) android.view.SurfaceView{5b436a VFE...C.. ........ 753,459-1053,759 #7f08002b app:id/camera_view_sub}
03-18 14:47:11.566 17077-17077/com.testRn.servicetest V/CameraFragment: onDestroy:
    onDetach:
03-18 14:47:11.571 17077-17133/com.testRn.servicetest D/OpenGLRenderer: eglDestroySurface = 0xd095e028
03-18 14:47:11.572 17077-17077/com.testRn.servicetest D/ViewRootImpl@c2e6e47[MainActivity]: dispatchDetachedFromWindow
03-18 14:47:11.572 17077-17077/com.testRn.servicetest D/InputEventReceiver: channel 'f650409 com.testRn.servicetest/com.testRn.servicetest.MainActivity (client)' ~ Disposing input event receiver.
    channel 'f650409 com.testRn.servicetest/com.testRn.servicetest.MainActivity (client)' ~NativeInputEventReceiver.
03-18 14:47:11.588 17077-17077/com.testRn.servicetest V/CameraFragment: Constructor:
    onAttach:
03-18 14:47:11.589 17077-17077/com.testRn.servicetest V/CameraFragment: onCreate:
03-18 14:47:11.625 17077-17077/com.testRn.servicetest V/CameraFragment: onCreateView:
03-18 14:47:11.677 17077-17077/com.testRn.servicetest V/CameraFragment: onResume:
03-18 14:47:11.677 17077-17088/com.testRn.servicetest I/zygote: Do partial code cache collection, code=23KB, data=30KB
03-18 14:47:11.678 17077-17088/com.testRn.servicetest I/zygote: After code cache collection, code=23KB, data=30KB
    Increasing code cache capacity to 128KB
    Do partial code cache collection, code=23KB, data=37KB
    After code cache collection, code=23KB, data=37KB
    Increasing code cache capacity to 256KB
03-18 14:47:11.712 17077-17077/com.testRn.servicetest D/ViewRootImpl@ffb2f94[MainActivity]: setView = DecorView@6ea8a3d[MainActivity] TM=true MM=false
03-18 14:47:11.764 17077-17077/com.testRn.servicetest D/ViewRootImpl@ffb2f94[MainActivity]: dispatchAttachedToWindow
03-18 14:47:11.773 17077-17088/com.testRn.servicetest I/zygote: Compiler allocated 5MB to compile void android.widget.TextView.<init>(android.content.Context, android.util.AttributeSet, int, int)
03-18 14:47:11.784 17077-17077/com.testRn.servicetest V/Surface: sf_framedrop debug : 0x4f4c, game : false, logging : 0
03-18 14:47:11.785 17077-17077/com.testRn.servicetest D/ViewRootImpl@ffb2f94[MainActivity]: Relayout returned: old=[0,0][0,0] new=[0,0][1920,1080] result=0x7 surface={valid=true 3518707712} changed=true
03-18 14:47:11.791 17077-17133/com.testRn.servicetest D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [1920x1080]-format:1
03-18 14:47:11.791 17077-17133/com.testRn.servicetest D/OpenGLRenderer: eglCreateWindowSurface = 0xd095ef28
03-18 14:47:11.808 17077-17077/com.testRn.servicetest D/SurfaceView: BG show() Surface(name=Background for - SurfaceView - com.testRn.servicetest/com.testRn.servicetest.MainActivity@96dc3f5@0) android.view.SurfaceView{96dc3f5 VFE...C.. ......ID 1205,27-1505,327 #7f08002b app:id/camera_view_sub}
03-18 14:47:11.816 17077-17077/com.testRn.servicetest V/Surface: sf_framedrop debug : 0x4f4c, game : false, logging : 0
03-18 14:47:11.816 17077-17077/com.testRn.servicetest D/SurfaceView: surfaceCreated 0 android.view.SurfaceView{96dc3f5 VFE...C.. ......ID 1205,27-1505,327 #7f08002b app:id/camera_view_sub}
    surfaceChanged (300,300) 0 android.view.SurfaceView{96dc3f5 VFE...C.. ......ID 1205,27-1505,327 #7f08002b app:id/camera_view_sub}
03-18 14:47:11.817 17077-17077/com.testRn.servicetest E/ViewRootImpl: sendUserActionEvent() returned.
03-18 14:47:11.830 17077-17077/com.testRn.servicetest D/ViewRootImpl@ffb2f94[MainActivity]: Relayout returned: old=[0,0][1920,1080] new=[0,0][1920,1080] result=0x3 surface={valid=true 3518707712} changed=false
03-18 14:47:11.836 17077-17077/com.testRn.servicetest V/Surface: sf_framedrop debug : 0x4f4c, game : false, logging : 0
03-18 14:47:11.836 17077-17077/com.testRn.servicetest V/UVCCameraTextureView: onSurfaceTextureAvailable:android.graphics.SurfaceTexture@c28a018
03-18 14:47:11.837 17077-17077/com.testRn.servicetest V/UVCCameraTextureView: RenderThread#getHandler:
03-18 14:47:11.837 17077-17306/com.testRn.servicetest D/UVCCameraTextureView: RenderThread started
03-18 14:47:11.837 17077-17306/com.testRn.servicetest V/UVCCameraTextureView: RenderThread#init:
03-18 14:47:11.838 17077-17306/com.testRn.servicetest D/EGLBase14: EGLContext created, client version 3
03-18 14:47:11.838 17077-17306/com.testRn.servicetest V/Surface: sf_framedrop debug : 0x4f4c, game : false, logging : 0
03-18 14:47:11.838 17077-17306/com.testRn.servicetest D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [1120x840]-format:1
03-18 14:47:11.859 17077-17077/com.testRn.servicetest D/ViewRootImpl@ffb2f94[MainActivity]: MSG_RESIZED_REPORT: frame=Rect(0, 0 - 1920, 1080) ci=Rect(0, 72 - 0, 0) vi=Rect(0, 72 - 0, 0) or=2
    MSG_WINDOW_FOCUS_CHANGED 1
03-18 14:47:11.863 17077-17077/com.testRn.servicetest V/InputMethodManager: Starting input: tba=android.view.inputmethod.EditorInfo@8a3aa71 nm : com.testRn.servicetest ic=null
03-18 14:47:11.863 17077-17077/com.testRn.servicetest I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
03-18 14:47:14.360 17077-17077/com.testRn.servicetest V/CameraFragment: onPause:
03-18 14:47:14.364 17077-17077/com.testRn.servicetest D/SurfaceView: BG show() Surface(name=Background for - SurfaceView - com.testRn.servicetest/com.testRn.servicetest.MainActivity@96dc3f5@0) android.view.SurfaceView{96dc3f5 VFE...C.. ........ 1205,27-1505,327 #7f08002b app:id/camera_view_sub}
03-18 14:47:14.365 17077-17077/com.testRn.servicetest D/SurfaceView: surfaceDestroyed 0 android.view.SurfaceView{96dc3f5 VFE...C.. ........ 1205,27-1505,327 #7f08002b app:id/camera_view_sub}
03-18 14:47:14.368 17077-17077/com.testRn.servicetest V/CameraFragment: onDestroyView:
03-18 14:47:14.369 17077-17077/com.testRn.servicetest V/UVCCameraTextureView: onSurfaceTextureDestroyed:android.graphics.SurfaceTexture@c28a018
    release:
03-18 14:47:14.369 17077-17306/com.testRn.servicetest D/UVCCameraTextureView: RenderThread finishing
03-18 14:47:14.369 17077-17306/com.testRn.servicetest V/UVCCameraTextureView: RenderThread#release:
03-18 14:47:14.379 17077-17077/com.testRn.servicetest D/SurfaceView: BG show() Surface(name=Background for - SurfaceView - com.testRn.servicetest/com.testRn.servicetest.MainActivity@96dc3f5@0) android.view.SurfaceView{96dc3f5 VFE...C.. ........ 1205,27-1505,327 #7f08002b app:id/camera_view_sub}
    BG destroy() Surface(name=Background for - SurfaceView - com.testRn.servicetest/com.testRn.servicetest.MainActivity@96dc3f5@0) android.view.SurfaceView{96dc3f5 VFE...C.. ........ 1205,27-1505,327 #7f08002b app:id/camera_view_sub}
03-18 14:47:14.380 17077-17077/com.testRn.servicetest V/CameraFragment: onDestroy:
    onDetach:
03-18 14:47:14.385 17077-17133/com.testRn.servicetest D/OpenGLRenderer: eglDestroySurface = 0xd095ef28
03-18 14:47:14.385 17077-17077/com.testRn.servicetest D/ViewRootImpl@ffb2f94[MainActivity]: dispatchDetachedFromWindow
03-18 14:47:14.385 17077-17077/com.testRn.servicetest D/InputEventReceiver: channel '75f8101 com.testRn.servicetest/com.testRn.servicetest.MainActivity (client)' ~ Disposing input event receiver.
03-18 14:47:14.386 17077-17077/com.testRn.servicetest D/InputEventReceiver: channel '75f8101 com.testRn.servicetest/com.testRn.servicetest.MainActivity (client)' ~NativeInputEventReceiver.
03-18 14:47:14.400 17077-17077/com.testRn.servicetest V/CameraFragment: Constructor:
03-18 14:47:14.400 17077-17077/com.testRn.servicetest V/CameraFragment: onAttach:
03-18 14:47:14.401 17077-17077/com.testRn.servicetest V/CameraFragment: onCreate:
03-18 14:47:14.429 17077-17077/com.testRn.servicetest V/CameraFragment: onCreateView:
03-18 14:47:14.452 17077-17088/com.testRn.servicetest I/zygote: Do full code cache collection, code=126KB, data=86KB
    After code cache collection, code=126KB, data=71KB
03-18 14:47:14.460 17077-17077/com.testRn.servicetest V/CameraFragment: onResume:
03-18 14:47:14.467 17077-17077/com.testRn.servicetest D/ViewRootImpl@3ec89a[MainActivity]: setView = DecorView@cf685cb[MainActivity] TM=true MM=false
03-18 14:47:14.479 17077-17077/com.testRn.servicetest D/ViewRootImpl@3ec89a[MainActivity]: dispatchAttachedToWindow
03-18 14:47:14.497 17077-17077/com.testRn.servicetest V/Surface: sf_framedrop debug : 0x4f4c, game : false, logging : 0
03-18 14:47:14.497 17077-17077/com.testRn.servicetest D/ViewRootImpl@3ec89a[MainActivity]: Relayout returned: old=[0,0][0,0] new=[0,0][1080,1920] result=0x7 surface={valid=true 3516921856} changed=true
03-18 14:47:14.499 17077-17133/com.testRn.servicetest D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [1080x1920]-format:1
03-18 14:47:14.499 17077-17133/com.testRn.servicetest D/OpenGLRenderer: eglCreateWindowSurface = 0xd095fb58
03-18 14:47:14.510 17077-17077/com.testRn.servicetest D/SurfaceView: BG show() Surface(name=Background for - SurfaceView - com.testRn.servicetest/com.testRn.servicetest.MainActivity@cafe343@0) android.view.SurfaceView{cafe343 VFE...C.. ......ID 753,459-1053,759 #7f08002b app:id/camera_view_sub}
03-18 14:47:14.518 17077-17077/com.testRn.servicetest V/Surface: sf_framedrop debug : 0x4f4c, game : false, logging : 0
03-18 14:47:14.518 17077-17077/com.testRn.servicetest D/SurfaceView: surfaceCreated 0 android.view.SurfaceView{cafe343 VFE...C.. ......ID 753,459-1053,759 #7f08002b app:id/camera_view_sub}
    surfaceChanged (300,300) 0 android.view.SurfaceView{cafe343 VFE...C.. ......ID 753,459-1053,759 #7f08002b app:id/camera_view_sub}
03-18 14:47:14.519 17077-17077/com.testRn.servicetest E/ViewRootImpl: sendUserActionEvent() returned.
03-18 14:47:14.527 17077-17077/com.testRn.servicetest D/ViewRootImpl@3ec89a[MainActivity]: Relayout returned: old=[0,0][1080,1920] new=[0,0][1080,1920] result=0x3 surface={valid=true 3516921856} changed=false
03-18 14:47:14.531 17077-17077/com.testRn.servicetest V/Surface: sf_framedrop debug : 0x4f4c, game : false, logging : 0
03-18 14:47:14.531 17077-17077/com.testRn.servicetest V/UVCCameraTextureView: onSurfaceTextureAvailable:android.graphics.SurfaceTexture@1fc0a3e
03-18 14:47:14.532 17077-17077/com.testRn.servicetest V/UVCCameraTextureView: RenderThread#getHandler:
03-18 14:47:14.532 17077-17319/com.testRn.servicetest D/UVCCameraTextureView: RenderThread started
03-18 14:47:14.532 17077-17319/com.testRn.servicetest V/UVCCameraTextureView: RenderThread#init:
03-18 14:47:14.532 17077-17319/com.testRn.servicetest D/EGLBase14: EGLContext created, client version 3
03-18 14:47:14.533 17077-17319/com.testRn.servicetest V/Surface: sf_framedrop debug : 0x4f4c, game : false, logging : 0
03-18 14:47:14.533 17077-17319/com.testRn.servicetest D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [1056x791]-format:1
03-18 14:47:14.546 17077-17077/com.testRn.servicetest D/ViewRootImpl@3ec89a[MainActivity]: MSG_RESIZED_REPORT: frame=Rect(0, 0 - 1080, 1920) ci=Rect(0, 72 - 0, 0) vi=Rect(0, 72 - 0, 0) or=1
    MSG_WINDOW_FOCUS_CHANGED 1
03-18 14:47:14.550 17077-17077/com.testRn.servicetest V/InputMethodManager: Starting input: tba=android.view.inputmethod.EditorInfo@d63709f nm : com.testRn.servicetest ic=null
03-18 14:47:14.550 17077-17077/com.testRn.servicetest I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
03-18 14:47:18.957 17077-17077/com.testRn.servicetest V/CameraFragment: onPause:
03-18 14:47:18.986 17077-17088/com.testRn.servicetest I/zygote: Do partial code cache collection, code=126KB, data=85KB
    After code cache collection, code=126KB, data=85KB
    Increasing code cache capacity to 512KB
03-18 14:47:18.988 17077-17077/com.testRn.servicetest D/ViewRootImpl@3ec89a[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 0
03-18 14:47:20.423 17077-17077/com.testRn.servicetest D/ViewRootImpl@3ec89a[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 1
03-18 14:47:20.426 17077-17077/com.testRn.servicetest V/InputMethodManager: Starting input: tba=android.view.inputmethod.EditorInfo@602edb5 nm : com.testRn.servicetest ic=null
03-18 14:47:20.426 17077-17077/com.testRn.servicetest I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
03-18 14:47:20.467 17077-17077/com.testRn.servicetest V/CameraFragment: onResume:
03-18 14:47:21.486 17077-17317/com.testRn.servicetest V/CameraFragment: OnDeviceConnectListener#onAttach:
03-18 14:47:21.489 17077-17317/com.testRn.servicetest V/CameraFragment: tryOpenUVCCamera:
    openUVCCamera:index=0
03-18 14:47:21.496 17077-17317/com.testRn.servicetest V/CameraClient: Constructor:
03-18 14:47:21.500 17077-17452/com.testRn.servicetest V/CameraClientThread: run:
03-18 14:47:21.501 17077-17317/com.testRn.servicetest V/CameraClient: doBindService:
03-18 14:47:21.506 17077-17317/com.testRn.servicetest V/CameraClient: select:device=/dev/bus/usb/001/002
03-18 14:47:21.506 17077-17452/com.testRn.servicetest V/CameraClientThread: handleSelect:
03-18 14:47:21.508 17077-17317/com.testRn.servicetest V/CameraClient: resize(640,480)
    connect:

**Comment by ghost** [comment]
@lvi166 Oh, I was stupid. I had missed one on the doBindService() side. I also changed it and I can see permission dialog. I really thank you for your reply.

**Comment by kolyadruz** [comment]
hi!

> @lvi166 Oh, I was stupid. I had missed one on the doBindService() side. I also changed it and I can see permission dialog. I really thank you for your reply.

Hi! What did you missed? Which line?

**Comment by ghost** [comment]
> hi!
> 
> > @lvi166 Oh, I was stupid. I had missed one on the doBindService() side. I also changed it and I can see permission dialog. I really thank you for your reply.
> 
> Hi! What did you missed? Which line?

Hello, I mean line 161 intent.setPackage("com.serenegiant.usbcameratest4");
in the UVCCamera/usbCameraTest4/src/main/java/com/serenegiant/serviceclient/CameraClient.java

I also have to change setPackage which I renamed.

**Comment by kolyadruz** [comment]
> Hello, I mean line 161 intent.setPackage("com.serenegiant.usbcameratest4");
> in the UVCCamera/usbCameraTest4/src/main/java/com/serenegiant/serviceclient/CameraClient.java
> 
> I also have to change setPackage which I renamed.

Thanks a lot for your fast reply! I've changed it, but my USB permission dialog isn't appear. Difference of projects in AndroidX, the new one using it. 

gradle plugin 3.4.0
ndk 14r
commonlib 2.12.4

**Comment by ghost** [comment]
> > Hello, I mean line 161 intent.setPackage("com.serenegiant.usbcameratest4");
> > in the UVCCamera/usbCameraTest4/src/main/java/com/serenegiant/serviceclient/CameraClient.java
> > I also have to change setPackage which I renamed.
> 
> Thanks a lot for your fast reply! I've changed it, but my USB permission dialog isn't appear. Difference of projects in AndroidX, the new one using it.
> 
> gradle plugin 3.4.0
> ndk 14r
> commonlib 2.12.4

I found my miss part with Find in path with whole project. I'm not sure, but you may have missed something! Search with test4.
