### ISSUE TITLE
bypassed permission dialog steel shows up after device restarted

### ISSUE THREAD

**Issue by developer--** [saki4510t/UVCCamera#451]
I have rooted device and app is installed as system app, when I accept permission once permission dialog doesn't shows up if I unplug the usb, but after restart it steel shows up. Is there anything in this lib which clears granted permission after restart or it is just android specific 

version is 5.0.1

**Comment by Akimeite** [comment]
modify the source code at here if you can:
**\frameworks\base\packages\SystemUI\src\com\android\systemui\usb\UsbPermissionActivity.java**
in **public void onCreate(Bundle icicle)**:
```java
//setupAlert();
mAlwaysUse.setChecked(true);
mPermissionGranted = true;
finish();
```
try it
