### ISSUE TITLE
How to import 'libuvccamera' and 'usbCameraCommon' to new project

### ISSUE THREAD

**Issue by icetea0822** [saki4510t/UVCCamera#491]
I'have put this 
    implementation("com.serenegiant:common:${commonLibVersion}") {
        exclude module: 'support-v4'
    }
and 
     maven { url 'http://raw.github.com/saki4510t/libcommon/master/repository/' }
to my project ,but i can't find module 'libuvccamera' and 'usbCameraCommon' ,how can i put this two modules to my project?
Thanks!

**Comment by Louis-smc** [comment]
copy libuvccamera and usbcameracommon to the same level as app folder
open settings.gradle, add the following 2 lines:

include ':libuvccamera'
include ':usbCameraCommon'

**Comment by icetea0822** [comment]
Thanks a lot

**Comment by EjazAmir** [comment]
hey, i did the same but i got some errors. 
AAPT: error: duplicate value for resource 'attr/orientation' with config ''.
AAPT: error: resource previously defined here.

kindly prvode any solution, im hell tried all things but no luck.
