### ISSUE TITLE
USBMonitor只能回调一次

### ISSUE THREAD

**Issue by icetea0822** [saki4510t/UVCCamera#500]
USB设备插拔一次后，设备插入拔出的回调则不执行，检查发现是USBMonitor类中，第506行，广播中每次收到usb插拔回调后都取消了广播，所以外面也就收不到广播了，注释掉即可。

**Comment by gxshao** [comment]
是master分支的代码吗。怎么没看到

**Comment by icetea0822** [comment]
我靠，还真没有，那我这个项目是哪来的
