### ISSUE TITLE
How can i connect camera without CameraDialog ?

### ISSUE THREAD

**Issue by Sattayapong** [saki4510t/UVCCamera#501]
I try module usbCameraTest0 to usbCameraTest8 every module has using CameraDialog for Preview Camera.

I want to auto-connect camera after activity onCreate, but I can't find a way to do it.

Please give me an advice concerning what to do.

thankyou.

**Comment by gxshao** [comment]
You can build your own `UVCCamera.aar` by `./gradlew build`. after building, you will find libuvccamera.aar under `UVCCamara/libuvccamera/build/outputs/aar/`

And include it into your project.

**Comment by Sattayapong** [comment]
thank you for your advice, I did it but I forgot to close.

**Comment by EjazAmir** [comment]
> thank you for your advice, I did it but I forgot to close.

hey, can you share the piece of code how you achieve this.

**Comment by EjazAmir** [comment]
> You can build your own `UVCCamera.aar` by `./gradlew build`. after building, you will find libuvccamera.aar under `UVCCamara/libuvccamera/build/outputs/aar/`
> 
> And include it into your project.

hey, can you share the piece of code how you achieve this.
