### ISSUE TITLE
finished with non-zero exit value 2

### ISSUE THREAD

**Issue by flybird333** [saki4510t/UVCCamera#510]
Process 'command 'C:\Users\Administrator\AppData\Local\Android\Sdk\ndk-bundle/ndk-build.cmd'' finished with non-zero exit value 2
when i run this project ，android studio has a mistake。

windows 10
android studio 3.3.2
ndk 20.0.5594570
com.android.tools.build:gradle:3.1.4
ext {
	supportLibVersion = '27.1.1'
	versionBuildTool = '27.0.3'
	versionCompiler = 27
	versionTarget = 27
	versionNameString = '1.0.0'
	javaSourceCompatibility = JavaVersion.VERSION_1_8
	javaTargetCompatibility = JavaVersion.VERSION_1_8
}

**Comment by hjhcs121** [comment]
i have the same issue！

**Comment by hjhcs121** [comment]
> i have the same issue！
this solve the problem
https://www.jianshu.com/p/e9b8eb2c3bd5

**Comment by flybird333** [comment]
APP_ABI := armeabi-v7a    
it work ， thank you ! @hjhcs121
