### ISSUE TITLE
Why is my native heap increasing?

### ISSUE THREAD

**Issue by alless1** [saki4510t/UVCCamera#517]
As I kept turning on and off the camera, I dumpsys meminfo showed that Native Heap was rising and could not be released. Not even calling GC. I'm sure I've completely freed up resources at the Java layer.
After testing, I found that this would not happen without setFrameCallback, but why?
Please help me, thank you.
@saki4510t

**Comment by yzq666** [comment]
I also encountered your problem. Thank you for your test. If you have any solution, please contact me. 
  846384016@qq.com

**Comment by yzq666** [comment]
yuanzuqiang@cvte.com

**Comment by alless1** [comment]
It's because I performed a mCamera.destroy() in the onFrame method; the native heap cannot be freed. It's amazing.

**Comment by alless1** [comment]
> I also encountered your problem. Thank you for your test. If you have any solution, please contact me.
> [846384016@qq.com](mailto:846384016@qq.com)
Do not release resources in callback threads
