### ISSUE TITLE
Resolution issue?

### ISSUE THREAD

**Issue by rgm-22** [saki4510t/UVCCamera#565]
**Great work! Thank you!**

I would like to modify the libraries because I am having this excepition:

I/AbsUVCCameraHandler: supportedSize:{"formats":[{"index":1,"type":4,"default":1,"size":["160x120"]},{"index":2,"type":4,"default":1,"size":["160x120","160x122"]},{"index":3,"type":4,"default":1,"size":["160x120"]},{"index":4,"type":4,"default":1,"size":["160x120"]},{"index":5,"type":4,"default":1,"size":["160x120"]}]}
V/zhf_debug: handleSetPreviewCallback: frameCallback=com.example.o0orick.camera.MainActivity$5@d9370d9
I/libUVCCamera: [14743*UVCPreview.cpp:266:callbackPixelFormatChanged]:PIXEL_FORMAT_RGB565:
V/CameraThread: handleStartPreview:
W/System.err: java.lang.IllegalArgumentException: Failed to set preview size
W/System.err: at com.serenegiant.usb.UVCCamera.setPreviewSize(UVCCamera.java:328)

With these values:

**private static final int PREVIEW_WIDTH = 160;
private static final int PREVIEW_HEIGHT = 120;
private static final int PREVIEW_MODE = 0; // YUV**

Any suggestion to solve it?

Thank you very much in advance

**Comment by feng612266** [comment]
> **Great work! Thank you!**
> 
> I would like to modify the libraries because I am having this excepition:
> 
> I/AbsUVCCameraHandler: supportedSize:{"formats":[{"index":1,"type":4,"default":1,"size":["160x120"]},{"index":2,"type":4,"default":1,"size":["160x120","160x122"]},{"index":3,"type":4,"default":1,"size":["160x120"]},{"index":4,"type":4,"default":1,"size":["160x120"]},{"index":5,"type":4,"default":1,"size":["160x120"]}]} V/zhf_debug: handleSetPreviewCallback: frameCallback=com.example.o0orick.camera.MainActivity$5@d9370d9 I/libUVCCamera: [14743*UVCPreview.cpp:266:callbackPixelFormatChanged]:PIXEL_FORMAT_RGB565: V/CameraThread: handleStartPreview: W/System.err: java.lang.IllegalArgumentException: Failed to set preview size W/System.err: at com.serenegiant.usb.UVCCamera.setPreviewSize(UVCCamera.java:328)
> 
> With these values:
> 
> **private static final int PREVIEW_WIDTH = 160; private static final int PREVIEW_HEIGHT = 120; private static final int PREVIEW_MODE = 0; // YUV**
> 
> Any suggestion to solve it?
> 
> Thank you very much in advance

hi,how resolve this question

**Comment by rgm-22** [comment]
Hi @feng612266,

What camera (specs) are you using?

It depends on your resolution and your video format.
