### ISSUE TITLE
How to solve the preview delay problem

### ISSUE THREAD

**Issue by along1991** [saki4510t/UVCCamera#605]

**Comment by along1991** [comment]
> 1080p 30fps mjpeg摄像机预览时间延迟为400ms，如何解决？

**Comment by zyowo** [comment]
我也有延迟相关的问题，请问您后来解决了吗？

**Comment by along1991** [comment]
> 我也有延迟相关的问题，请问您后来解决了吗？

解决了,问题出再mjpeg转码yuyv再转码rgb这里耗时很久,,我这里使用libyuv库,mjpeg转码i420再转码abgr,延时降低到了130ms

**Comment by YZ-Inspify** [comment]
@along1991 - 请问有示例代码如何把获得的`uvc_frame`在libyuv中mjpeg转i420再转abgr吗？

多谢帮助！

**Comment by along1991** [comment]
> @along1991 - 有示例代码如何把获得的`uvc_frame`在libyuv中mjpeg转i420再转abgr吗？
> 
> 多谢帮助！
参考这篇文章https://blog.csdn.net/xuhui_7810/article/details/103741722?
里面搜MJPGToI420就行

**Comment by liubilly2021** [comment]
大家好，android uvccamera MJPEG 2592x1944 预览延迟有400ms ，分辨率越高，延迟约到，请大家帮忙看看，怎么优化。

**Comment by liubilly2021** [comment]
> > 我也有延迟相关的问题，请问您后来解决了吗？
> 
> 解决了,问题出再mjpeg转码yuyv再转码rgb这里耗时很久,,我这里使用libyuv库,mjpeg转码i420再转码abgr,延时降低到了130ms

你好，这个有参考到吗放出来吗

**Comment by along1991** [comment]
你用usb测一下延时，就是沈垚的那个https://app.xiaomi.com/details?id=com.shenyaocn.android.usbcamera，看下延时是多少，如果差不多就不用改了，如果差的比较多，那就改改



---Original---
From: ***@***.***&gt;
Date: Mon, Nov 28, 2022 16:53 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [saki4510t/UVCCamera] How to solve the preview delay problem(#605)

**Comment by zhouqunhuang** [comment]
你好请问你能帮我解决一下吗？我在4K上延迟有一两秒。如果解决成功给你报酬。我的QQ：1134364286有意向叫我价格可谈

**Comment by zjmsky** [comment]
> 你好请问你能帮我解决一下吗？我在4K上延迟有一两秒。如果解决成功给你报酬。我的QQ：1134364286有意向叫我价格可谈

请教下，延迟的问题解决了吗

**Comment by zhouqunhuang** [comment]
没有啊！我们公司最后外包出去了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2025年8月18日(星期一) 下午2:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [saki4510t/UVCCamera] How to solve the preview delay problem (#605)












zjmsky left a comment (saki4510t/UVCCamera#605)
  
你好请问你能帮我解决一下吗？我在4K上延迟有一两秒。如果解决成功给你报酬。我的QQ：1134364286有意向叫我价格可谈
  
请教下，延迟的问题解决了吗

**Comment by zjmsky** [comment]
> 没有啊！我们公司最后外包出去了
> […](#)

感谢。
