### ISSUE TITLE
Google vulnerabilty for libjpeg-turbo 

### ISSUE THREAD

**Issue by ericeche** [saki4510t/UVCCamera#64]
https://support.google.com/faqs/answer/7008337

Google suggests to update to libjpeg-turbo v1.4.2 or greater. Any idea how to do the update ?

**Comment by ericeche** [comment]
Here is the git repo with update:
https://github.com/libjpeg-turbo/libjpeg-turbo

**Comment by saki4510t** [comment]
Hi,
I replaced libjpeg-turbo 1.4.0 with 1.5.0. please try latest master branch.

**Comment by ericeche** [comment]
Thanks for your prompt reply

**Comment by ericeche** [comment]
What happen with mips build ? May I ask why it was taken out of the build. Just curiosity

**Comment by saki4510t** [comment]
Hi,
There are few devices that SOC is powered by mips.  As I know there are no mips powered smartphone/tablet in Japan and I also don't have.  This means I can't confirm whether these libraries work on the devices or not. So originally I have not support mips but someone added it on pull request.  
I added settings for mips now but it is just for convenience and I'm not sure it works on mips powered devices.

**Comment by ybdesale-vanlentsystems** [comment]
@saki4510t I want to upgrade libjpeg-turbo 1.5.0 with 2.1.5. Please suggest the changes. I had tried but not able to do that. @ericeche you can also help if you have any idea about this.
