### ISSUE TITLE
how can i use it on arm64 - v8a phone

### ISSUE THREAD

**Issue by HeMing123** [saki4510t/UVCCamera#71]

**Comment by saki4510t** [comment]
Hi,
You can add `arm64-v8a` to `APP_ABI` on `Application.mk` on `libuvccamera` module or use `APP_ABI := all`.
But as I test there are few benefit to use  `arm64-v8a` and sometimes it increase memory usage and become slower than `armeabi-v7a`.
saki

**Comment by HeMing123** [comment]
thanks
