### ISSUE TITLE
How to get QR code

### ISSUE THREAD

**Issue by jp1017** [saki4510t/UVCCamera#74]
So, how to get QR code message when previewing a QR image.

**Comment by saki4510t** [comment]
Hi,
For several years before, I had tried to use `ZXing` with UVC camera and worked.

**Comment by jp1017** [comment]
@saki4510t Hi, can you show some codes. :+1:

**Comment by jp1017** [comment]
demo: https://github.com/jp1017/UVCCameraZxing
