### ISSUE TITLE
how to record video every 10 minutes 

### ISSUE THREAD

**Issue by lsy17096535** [saki4510t/UVCCamera#79]
hi, saki4510t
    Thanks for your project. when use Timer in project usbcameratest4 to get video every 10 minutes, I found that the muxer will not be released. When i start a new video, the former one have not be closed.
when i push the stopservice button, the code will close the video completely. could you tell me how to record video every 10 minutes in usbcameratest4? thanks again.
                                                                              syan

**Comment by jp1017** [comment]
@lsy17096535 The latested version makes well. :smile:

**Comment by jp1017** [comment]
@lsy17096535 like this: 

https://github.com/saki4510t/UVCCamera/issues/73

**Comment by lsy17096535** [comment]
@jp1017 Thank you !
