### ISSUE TITLE
Zoom Functionality

### ISSUE THREAD

**Issue by h777arsh** [saki4510t/UVCCamera#94]
Hello @saki4510t, First of all nice work.

My Question is how we can implement zoom functionality with two finger gesture in usbCameraTest7 sample.

Thanks.

**Comment by jp1017** [comment]
Have you solved it? @h777arsh

**Comment by h777arsh** [comment]
I was developing for VR, I need to zoom view, no camera zoom. so for that, I used scale factor as per user pinch gesture, so both camera view scale at the same time.

**Comment by shashankjamdade** [comment]
setZoom(final int zoom) is not working. I want to zoom the camara not the view. How can I do so?? Please help me as soon as possible.

**Comment by shashankjamdade** [comment]
go through the comment of the issue #367
