### ISSUE TITLE
Android TV

### ISSUE THREAD

**Issue by huanghm** [saki4510t/UVCCamera#99]
Hello, I have found on Android TV can't get usb camera device, the Android TV with usb interface

**Comment by saki4510t** [comment]
Hi,

That is normal behavior. Because Android TV usually treats USB connected camera as internal camera and can not use it as UVC device (almost as same as on Android emulator on PC)
So you can't use it via this library and you need to use it as internal camera (via camera/camera2 API).

**Comment by huanghm** [comment]
そうですね ありがとう
